// splitCategories.js
require('dotenv').config();
const fs = require('fs');
const path = require('path');
const db = require('./config/database'); // Apna DB path set karein

async function runFilter() {
    console.log("🚀 Starting Database Filter & File Generator...");

    const inputFilePath = path.join(__dirname, 'productlinks.txt');
    const outputDir = path.join(__dirname, 'Pending_Categories');

    // Create output folder if not exists
    if (!fs.existsSync(outputDir)) {
        fs.mkdirSync(outputDir);
    }

    if (!fs.existsSync(inputFilePath)) {
        console.log("❌ productlinks.txt not found!");
        return process.exit(1);
    }

    // Read the file generated by browser
    const fileContent = fs.readFileSync(inputFilePath, 'utf-8');
    
    // Split the file into blocks based on "==="
    const blocks = fileContent.split('===').filter(b => b.trim() !== '');

    for (let i = 0; i < blocks.length; i += 2) {
        let categoryHeader = blocks[i].trim(); // e.g., "Cosmetics -> Skin Care"
        let linksBlock = blocks[i + 1]?.trim();

        if (!categoryHeader || !linksBlock) continue;

        let subCategoryName = categoryHeader.split('->')[1]?.trim();
        if (!subCategoryName) continue;

        console.log(`\n🔍 Checking DB for: ${subCategoryName}`);

        try {
            // Find category ID in DB using simple LIKE (ignoring exact caps/spaces)
            const [catRows] = await db.inventory.query(
                `SELECT id, name FROM categories WHERE LOWER(REPLACE(name, ' ', '')) = ? LIMIT 1`,
                [subCategoryName.toLowerCase().replace(/ /g, '')]
            );

            if (catRows.length === 0) {
                console.log(`⚠️ Category not found in DB. Creating file anyway so you don't miss it.`);
                createFile(outputDir, subCategoryName, linksBlock);
                continue;
            }

            const catId = catRows[0].id;

            // Check how many products are in Oracle DB
            const countRes = await db.oracle.query(
                "SELECT COUNT(*) as total FROM products WHERE category_id = $1", 
                [catId]
            );
            const productCount = parseInt(countRes.rows[0].total);

            if (productCount >= 10) {
                console.log(`⏭️ SKIP: ${subCategoryName} already has ${productCount} products.`);
            } else {
                console.log(`✅ NEEDS SCRAPING: ${subCategoryName} has only ${productCount} products. Generating file...`);
                createFile(outputDir, subCategoryName, linksBlock);
            }

        } catch (error) {
            console.error(`Error processing ${subCategoryName}:`, error.message);
        }
    }

    console.log(`\n🎉 Process Complete! Check the 'Pending_Categories' folder.`);
    process.exit(0);
}

// Helper to create txt files
function createFile(folder, name, content) {
    const safeName = name.replace(/[^a-zA-Z0-9]/g, '_'); // Remove illegal chars for filenames
    const filePath = path.join(folder, `${safeName}.txt`);
    fs.writeFileSync(filePath, content);
}

runFilter();